### ISSUE TITLE
Add support for protobuf editions

### ISSUE THREAD

**Issue by MaxProfit** [bufbuild/protovalidate-go#146]
**Feature description:** 
Protobuf editions should be supported

**Problem it solves or use case:** 
As it seems to be the next move for the protobuf syntax, this library should move to support the new syntax and changes. My current error is as follows.
> Failure: plugin "buf.build/bufbuild/validate-go" does not support feature "supports editions" which is required by "my.proto"

**Proposed implementation or solution:** 
Implement the changes as [specified by the edition 2023](https://protobuf.dev/editions/implementation/) to start.

**Contribution:**
I might be able to take this on when I get some time, but I can definitely help others if they're willing to take it on in any way I can.

**Examples or references:** 
N/A

**Additional context:** 
Should be pretty self-explanatory, feel free to ping me if any questions

**Comment by jhump** [comment]
@MaxProfit, this repo does not have any proto plugins. The plugin you referenced is actually for this repo: https://github.com/bufbuild/protoc-gen-validate

Note that repo is deprecated. This repo is its replacement. This repo relies on runtime reflection, not code generation. And it does support Editions. We highly recommend upgrading.

When you upgrade, you can even leave the existing annotations in your protos and just include [legacy support](https://github.com/bufbuild/protovalidate-go?tab=readme-ov-file#support-legacy-protoc-gen-validate-constraints) when you create a validator. Note however that the legacy support is purely transitional -- you should _also_ update all of your proto sources to use the new custom options, but you can do that over time instead of having to do everything at once (or worse, have both annotations on everything for some period). We plan to eventually _drop_ the legacy support, in a final v1.0 of this repo, so you'll need to migrate your options over (which should be mechanical and fairly painless) before you could upgrade to a future v1.0.

**Comment by rodaine** [comment]
Adding onto @jhump's response about legacy support, protovalidate also has a [migration utility](https://github.com/bufbuild/protovalidate/blob/main/docs/migrate.md) that will perform the updates from PGV to protovalidate for you.

**Comment by MaxProfit** [comment]
@jhump my bad! In my buf.gen.yaml I'm using both protovalidate and validate-go without even noticing. I think my original confusion might've come from the fact that https://buf.build/plugins doesn't reference protovalidate, so I jumped from that repo link saying that it was deprecated and moving to protovalidate, then came back and added validate-go thinking that was still the plugin. Thank you for clearing this up for me!
